name: Java CI
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'

      - name: Build Wolfo
        run: ./gradlew clean build

      - name: Upload build
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Wolfo-Artifact
          path: build/libs/Wolfo-1.0.0.jar